Added changelog command in general
payload-bot/payload-neo pull request #100
Opened 2021-10-02 02:09 UTC by satvik-1203

In addition to adding the changelog, Also added getArgs and getChangelog in src/util

2021-10-02 02:12 UTC, c43721 requested changes
2 things

2021-10-02 02:12 UTC, c43721 commented on src/commands/General/changelog.ts
> +    const [version] = getArgs(args);
We should use the sapphire args instead:

```
await args.pick("string").catch(() => null)
```

2021-10-02 02:12 UTC, c43721 commented on src/util/get-args.ts
> +import type { Args } from "@sapphire/framework";
We don't need this file, sapphire has args already for us

2021-10-02 02:21 UTC, c43721 requested changes
2 more nitpicks

2021-10-02 02:21 UTC, c43721 commented on src/util/get-changelog.ts
> +export async function getChangelog(version: string) {
let's make this function return `string | null` instead of `string | boolean`.

2021-10-02 02:21 UTC, c43721 commented on src/commands/General/changelog.ts
> +    const changeLog = await getChangelog(version);
Make sure to check if version is null here

2021-10-02 02:30 UTC, c43721 requested changes

2021-10-02 02:30 UTC, c43721 commented on src/commands/General/changelog.ts
> +    const [version] = argStr.split(" ");
Why do we need this? `getChangelog` acceps a version string, not an array.

2021-10-02 02:30 UTC, c43721 commented on src/util/get-changelog.ts
> +        encoding: "utf8",
Encoding is defaulted to `utf-8`, no?

2021-10-02 02:31 UTC, satvik-1203 commented on src/util/get-changelog.ts
> +        encoding: "utf8",
no the default is buffer

2021-10-02 02:31 UTC, satvik-1203 commented on src/commands/General/changelog.ts
> +    const [version] = argStr.split(" ");
right

2021-10-02 02:35 UTC, c43721 commented on src/util/get-changelog.ts
> +        encoding: "utf8",
😠

2021-10-02 18:35 UTC, satvik-1203 commented
Should check for permissions when purging messages or do that later?

2021-10-02 19:06 UTC, satvik-1203 commented
```JS
 if (args === false) {
      return false;
    }
```
I found that line in rtd from the master branch, I don't think we need it here. done with rtd as well :)

2021-10-02 19:27 UTC, c43721 requested changes
Nit picks and general code quality improvements

2021-10-02 19:27 UTC, c43721 commented on src/commands/Fun/rtd.ts
> +      dice.push(random(1, Math.round(Number(sides))));
Why do we need castings here? We have strong types for `sides` and `amount`, so the cast with the `Math.round` is unneeded.

We should make this into a map instead as well, or do a for-of loop instead for readability.

2021-10-02 19:27 UTC, c43721 commented on src/commands/General/changelog.ts
> +    if (!changeLog)
Nit: Wrap in braces if it wraps to new-line.

2021-10-02 19:27 UTC, c43721 commented on src/commands/General/profile.ts
> +    if (!user) {
We don't care if a user is not in database. Use `??` operator to set defaults instead.

2021-10-02 19:27 UTC, c43721 commented on src/commands/General/profile.ts
> +    let user = await User.findOne({ id: profile.id });
Needs `.lean().exec()` options.

2021-10-02 19:27 UTC, c43721 commented on src/commands/General/profile.ts
> +    const profile = await args.pick("user").catch(() => msg.author);
Nit: better naming: `targedUser`

2021-10-02 19:27 UTC, c43721 commented on src/commands/General/profile.ts
> +    ID: ${profile.id}
This ID should come from the targed user instead.

2021-10-02 19:27 UTC, c43721 commented on src/commands/General/profile.ts
> +    Points: 0
`Points: ${user.points ?? 0}`

2021-10-02 19:27 UTC, c43721 commented on src/commands/General/purge.ts
> +    if (!amount) return;
Remove this check and do a `catch` and set a default arg instead (100 default is good).

2021-10-02 19:27 UTC, c43721 commented on src/commands/General/purge.ts
> +      limit: 100,
Limit should be based on `amount`

2021-10-02 19:27 UTC, c43721 commented on src/commands/General/purge.ts
> +    const users = msg.mentions.users;
Don't do this- use `args` instead:
`const targetUserToRemove = await args.rest("member")`

2021-10-02 19:27 UTC, c43721 commented on src/commands/General/purge.ts
> +        .slice(0, amount as number)
Unneeded typecase to number here- `amount` is of type `number`

2021-10-02 19:27 UTC, c43721 commented on src/commands/General/purge.ts
> +})
Add a `runIn` option with `guildText` please.

2021-10-02 19:27 UTC, c43721 commented on src/commands/General/purge.ts
> +    if (users.size > 0) {
Make this so if no `targetedUsers`, then skip

2021-10-02 19:27 UTC, c43721 commented on src/util/get-changelog.ts
> +  if (!version.match(/\d+\.\d+.\d+/)) return false;
return nulls please instead

2021-10-02 19:27 UTC, c43721 commented on package.json
> +    "date-fns": "^2.24.0",
Btw, when doing PRs like this, try not to do side effects like this. Keep it focused, NPM packages should be left as is unless it's the task of the PR.

2021-10-02 19:27 UTC, c43721 commented on src/commands/General/profile.ts
> +import type { Args } from "@sapphire/framework";
Nit, duplicated imports

2021-10-02 19:27 UTC, c43721 commented on src/commands/General/purge.ts
> +import type { TextChannel } from "discord.js";
Nit, duplicated imports

2021-10-02 19:27 UTC, c43721 commented on src/commands/General/profile.ts
> +import { MessageEmbed } from "discord.js";
Nit, duplication imports

2021-10-02 19:35 UTC, satvik-1203 commented on src/commands/General/profile.ts
> +    if (!user) {
if a user is not in the DB, we should save them, right? I forgot to save them

2021-10-02 20:39 UTC, c43721 commented on src/commands/General/profile.ts
> +    if (!user) {
No, we cannot do that. We should only save them to the DB when they use commands that need the DB (pushcart in this case). This is intentional.

2021-10-03 00:03 UTC, satvik-1203 commented on src/commands/Fun/rtd.ts
> +      dice.push(random(1, Math.round(Number(sides))));
I don't think we can make it into a map or for of loop, we need elements in it to map it. 
Tried doing this but no luck
```TS
const dice: number[] = new Array(amount);
dice.forEach((_, index) => (dice[index] = random(1, sides)));
```
So should I just stick with for loop now?

2021-10-03 00:12 UTC, satvik-1203 commented on src/commands/General/profile.ts
> +    const profile = await args.pick("user").catch(() => msg.author);
hmm, is targed a word? or should I put targetUser?

2021-10-03 00:38 UTC, satvik-1203 commented on src/commands/General/purge.ts
> +    const users = msg.mentions.users;
but this doesn't return an array of all the mentions the user does

2021-10-03 00:54 UTC, satvik-1203 commented on src/commands/General/profile.ts
> +import { MessageEmbed } from "discord.js";
the app is on `typescript: 4.4.2`, so we can do then after updating the packages

2021-10-03 00:57 UTC, satvik-1203 commented on package.json
> +    "date-fns": "^2.24.0",
alright, I'll put it back to `.23`

2021-10-03 16:06 UTC, satvik-1203 commented
I left it as `msg.mentions.users` for now

2021-10-03 16:43 UTC, c43721 requested changes
Last stretch

2021-10-03 16:43 UTC, c43721 commented on src/commands/Fun/rtd.ts
> +    const amount = Math.round(await args.pick("number").catch(() => 1));
Don't round these. `number` takes care of that for us.

2021-10-03 16:43 UTC, c43721 commented on src/commands/Fun/rtd.ts
> +    for (let i = 0; i < amount; i++) dice.push(random(1, sides));
Convert to `for-of` loop please.

2021-10-03 16:43 UTC, c43721 commented on src/commands/General/changelog.ts
> +    // This error should be invalid version rather than saying Invalid version format
Good comment, but doesn't belong in here now.

Should remove.

2021-10-03 16:43 UTC, c43721 commented on src/commands/General/profile.ts
> +import { MessageEmbed } from "discord.js";
combine the djs imports into 1 line.

2021-10-03 16:43 UTC, c43721 commented on src/commands/General/profile.ts
> +      new User({ id: targetUser.id });
No creating users. Remove. Also, make user a `const`

2021-10-03 16:43 UTC, c43721 commented on src/commands/General/purge.ts
> +        Date.now() - channelMessage.createdTimestamp < 1000 * 60 * 60 * 24 * 14
extract the `1000 * 60 * 60 * 24 * 14` to a const outside of the class to prevent re-calculation during command (we want that extra .14ns improvement here)

2021-10-03 17:10 UTC, satvik-1203 commented on src/commands/Fun/rtd.ts
> +    for (let i = 0; i < amount; i++) dice.push(random(1, sides));
I don't think we can make it `for-of` loop 🤔

2021-10-04 01:16 UTC, c43721 requested changes
More nits

2021-10-04 01:16 UTC, c43721 commented on src/commands/General/profile.ts
> +    const user = (await User.findOne({ id: id }).lean().exec()) ?? {};
You do not need to nullcheck here, it's done below

2021-10-04 01:16 UTC, c43721 commented on src/commands/General/purge.ts
> +const fourteenDays = 1000 * 60 * 60 * 24 * 14;
name this `twoWeeks`

2021-10-04 01:44 UTC, c43721 approved these changes
LGTM

2021-10-04 01:45 UTC, merged